export interface DocumentInfo {
  slug: string;
  label_en: string;
  label_hi: string;
  description_en: string;
  description_hi: string;
  where_to_get_en: string;
  where_to_get_hi: string;
}

export const DOCUMENT_REGISTRY: Record<string, DocumentInfo> = {
  aadhaar: {
    slug: "aadhaar",
    label_en: "Aadhaar Card",
    label_hi: "आधार कार्ड",
    description_en: "12-digit unique identity number issued by UIDAI.",
    description_hi: "यूआईडीएआई द्वारा जारी 12 अंकों की विशिष्ट पहचान संख्या।",
    where_to_get_en: "UIDAI enrolment centre, post office, or download from myaadhaar.uidai.gov.in",
    where_to_get_hi: "यूआईडीएआई केंद्र, डाकघर, या myaadhaar.uidai.gov.in से डाउनलोड करें",
  },
  pan_card: {
    slug: "pan_card",
    label_en: "PAN Card",
    label_hi: "पैन कार्ड",
    description_en: "Permanent Account Number for tax and financial identity.",
    description_hi: "कर और वित्तीय पहचान के लिए स्थायी खाता संख्या।",
    where_to_get_en: "Apply at NSDL or UTIITSL portal or nearest PAN service centre",
    where_to_get_hi: "एनएसडीएल/यूटीआईआईटीएसएल पोर्टल या नजदीकी पैन केंद्र पर आवेदन करें",
  },
  pan_or_voter_id: {
    slug: "pan_or_voter_id",
    label_en: "PAN Card or Voter ID",
    label_hi: "पैन कार्ड या मतदाता पहचान पत्र",
    description_en: "Either PAN or Voter ID as secondary identity proof.",
    description_hi: "द्वितीयक पहचान प्रमाण के रूप में पैन या मतदाता पहचान पत्र।",
    where_to_get_en: "Election Commission office (Voter ID) or Income Tax portal (PAN)",
    where_to_get_hi: "निर्वाचन कार्यालय (मतदाता पत्र) या आयकर पोर्टल (पैन)",
  },
  bpl_card: {
    slug: "bpl_card",
    label_en: "BPL / Ration Card",
    label_hi: "बीपीएल / राशन कार्ड",
    description_en: "Below Poverty Line ration card proving economic status.",
    description_hi: "आर्थिक स्थिति सिद्ध करने वाला बीपीएल राशन कार्ड।",
    where_to_get_en: "State Food & Civil Supplies department or e-District portal",
    where_to_get_hi: "राज्य खाद्य एवं नागरिक आपूर्ति विभाग या ई-डिस्ट्रिक्ट पोर्टल",
  },
  ration_card: {
    slug: "ration_card",
    label_en: "Ration Card",
    label_hi: "राशन कार्ड",
    description_en: "Family ration card for subsidized food grains.",
    description_hi: "सब्सिडी वाले खाद्यान्न के लिए पारिवारिक राशन कार्ड।",
    where_to_get_en: "Local ration office or state PDS portal",
    where_to_get_hi: "स्थानीय राशन कार्यालय या राज्य पीडीएस पोर्टल",
  },
  income_certificate: {
    slug: "income_certificate",
    label_en: "Income Certificate",
    label_hi: "आय प्रमाण पत्र",
    description_en: "Certificate stating annual family income, issued by Tehsildar.",
    description_hi: "तहसीलदार द्वारा जारी वार्षिक पारिवारिक आय प्रमाण पत्र।",
    where_to_get_en: "Tehsildar office, e-District portal, or Common Service Centre",
    where_to_get_hi: "तहसीलदार कार्यालय, ई-डिस्ट्रिक्ट पोर्टल, या सामान्य सेवा केंद्र",
  },
  bank_passbook: {
    slug: "bank_passbook",
    label_en: "Bank Passbook / Account Details",
    label_hi: "बैंक पासबुक / खाता विवरण",
    description_en: "Active bank account with name matching Aadhaar.",
    description_hi: "आधार से मेल खाता नाम वाला सक्रिय बैंक खाता।",
    where_to_get_en: "Your bank branch — Jan Dhan accounts also accepted",
    where_to_get_hi: "आपकी बैंक शाखा — जन धन खाता भी मान्य",
  },
  caste_certificate: {
    slug: "caste_certificate",
    label_en: "Caste Certificate",
    label_hi: "जाति प्रमाण पत्र",
    description_en: "SC/ST/OBC certificate from competent authority.",
    description_hi: "सक्षम प्राधिकारी से एससी/एसटी/ओबीसी प्रमाण पत्र।",
    where_to_get_en: "Tehsildar or SDM office; apply via state e-District",
    where_to_get_hi: "तहसीलदार या एसडीएम कार्यालय; राज्य ई-डिस्ट्रिक्ट से आवेदन",
  },
  obc_certificate: {
    slug: "obc_certificate",
    label_en: "OBC Certificate",
    label_hi: "ओबीसी प्रमाण पत्र",
    description_en: "Other Backward Class certificate for reservation benefits.",
    description_hi: "आरक्षण लाभ के लिए अन्य पिछड़ा वर्ग प्रमाण पत्र।",
    where_to_get_en: "Tehsildar office or state backward classes welfare portal",
    where_to_get_hi: "तहसीलदार कार्यालय या राज्य पिछड़ा वर्ग कल्याण पोर्टल",
  },
  land_record: {
    slug: "land_record",
    label_en: "Land Ownership Record (7/12 / Khata)",
    label_hi: "भूमि स्वामित्व रिकॉर्ड (7/12 / खाता)",
    description_en: "Official land record showing ownership and area.",
    description_hi: "स्वामित्व और क्षेत्र दर्शाने वाला आधिकारिक भूमि रिकॉर्ड।",
    where_to_get_en: "Revenue department, Bhulekh portal, or Tehsildar office",
    where_to_get_hi: "राजस्व विभाग, भूलेख पोर्टल, या तहसीलदार कार्यालय",
  },
  land_document: {
    slug: "land_document",
    label_en: "Land / Property Document",
    label_hi: "भूमि / संपत्ति दस्तावेज़",
    description_en: "Proof of land ownership or plot details for housing schemes.",
    description_hi: "आवास योजनाओं के लिए भूमि स्वामित्व या प्लॉट विवरण।",
    where_to_get_en: "Revenue records office or state land records portal",
    where_to_get_hi: "राजस्व रिकॉर्ड कार्यालय या राज्य भूमि रिकॉर्ड पोर्टल",
  },
  property_document: {
    slug: "property_document",
    label_en: "Property / Sale Deed",
    label_hi: "संपत्ति / बिक्री विलेख",
    description_en: "Registered property document for urban housing loans.",
    description_hi: "शहरी आवास ऋण के लिए पंजीकृत संपत्ति दस्तावेज़।",
    where_to_get_en: "Sub-Registrar office where property was registered",
    where_to_get_hi: "उप-पंजीयक कार्यालय जहाँ संपत्ति पंजीकृत है",
  },
  death_certificate: {
    slug: "death_certificate",
    label_en: "Death Certificate",
    label_hi: "मृत्यु प्रमाण पत्र",
    description_en: "Official death certificate from municipal or panchayat authority.",
    description_hi: "नगरपालिका या पंचायत से आधिकारिक मृत्यु प्रमाण पत्र।",
    where_to_get_en: "Municipal corporation, gram panchayat, or Civil Registration System",
    where_to_get_hi: "नगर निगम, ग्राम पंचायत, या जन्म-मृत्यु पंजीकरण प्रणाली",
  },
  husband_death_certificate: {
    slug: "husband_death_certificate",
    label_en: "Death Certificate of Husband",
    label_hi: "पति का मृत्यु प्रमाण पत्र",
    description_en: "Required for widow pension and survivor benefits.",
    description_hi: "विधवा पेंशन और उत्तरजीवी लाभ के लिए आवश्यक।",
    where_to_get_en: "Registrar of births & deaths in husband's place of death",
    where_to_get_hi: "पति की मृत्यु स्थान के जन्म-मृत्यु पंजीयक से",
  },
  mark_sheet: {
    slug: "mark_sheet",
    label_en: "Latest Mark Sheet / Certificates",
    label_hi: "नवीनतम अंकपत्र / प्रमाणपत्र",
    description_en: "Academic marksheet for scholarship applications.",
    description_hi: "छात्रवृत्ति आवेदन के लिए शैक्षणिक अंकपत्र।",
    where_to_get_en: "School or college examination board",
    where_to_get_hi: "स्कूल या कॉलेज परीक्षा बोर्ड",
  },
  admission_letter: {
    slug: "admission_letter",
    label_en: "Admission / Enrollment Letter",
    label_hi: "प्रवेश / नामांकन पत्र",
    description_en: "Proof of current enrollment in an educational institution.",
    description_hi: "शैक्षणिक संस्थान में वर्तमान नामांकन का प्रमाण।",
    where_to_get_en: "College or university admission office",
    where_to_get_hi: "कॉलेज या विश्वविद्यालय प्रवेश कार्यालय",
  },
  age_proof: {
    slug: "age_proof",
    label_en: "Age Proof",
    label_hi: "आयु प्रमाण",
    description_en: "Birth certificate, school leaving certificate, or Aadhaar with DOB.",
    description_hi: "जन्म प्रमाण पत्र, स्कूल छोड़ने का प्रमाणपत्र, या जन्मतिथि वाला आधार।",
    where_to_get_en: "School records, municipal birth certificate, or Aadhaar",
    where_to_get_hi: "स्कूल रिकॉर्ड, नगरपालिका जन्म प्रमाण पत्र, या आधार",
  },
  school_certificate: {
    slug: "school_certificate",
    label_en: "School Enrollment Certificate",
    label_hi: "स्कूल नामांकन प्रमाण पत्र",
    description_en: "Bonafide certificate from school headmaster.",
    description_hi: "स्कूल प्रधानाध्यापक से बोनाफाइड प्रमाण पत्र।",
    where_to_get_en: "School administration office",
    where_to_get_hi: "स्कूल प्रशासन कार्यालय",
  },
  address_proof: {
    slug: "address_proof",
    label_en: "Address Proof",
    label_hi: "पता प्रमाण",
    description_en: "Utility bill, ration card, or rent agreement with address.",
    description_hi: "बिजली बिल, राशन कार्ड, या किरायानामा।",
    where_to_get_en: "Electricity/water bill, ration card, or notarized rent agreement",
    where_to_get_hi: "बिजली/पानी बिल, राशन कार्ड, या नोटरीकृत किरायानामा",
  },
  business_plan: {
    slug: "business_plan",
    label_en: "Business Plan / Project Report",
    label_hi: "व्यवसाय योजना / परियोजना रिपोर्ट",
    description_en: "Brief plan describing business activity and loan purpose.",
    description_hi: "व्यवसाय गतिविधि और ऋण उद्देश्य वर्णित संक्षिप्त योजना।",
    where_to_get_en: "Prepare yourself or get help from MSME/DIC office",
    where_to_get_hi: "स्वयं तैयार करें या एमएसएमई/डीआईसी कार्यालय से सहायता लें",
  },
  mobile_number: {
    slug: "mobile_number",
    label_en: "Aadhaar-linked Mobile Number",
    label_hi: "आधार से जुड़ा मोबाइल नंबर",
    description_en: "Active mobile number linked to Aadhaar for OTP verification.",
    description_hi: "ओटीपी सत्यापन के लिए आधार से जुड़ा सक्रिय मोबाइल नंबर।",
    where_to_get_en: "Link at telecom store or via Aadhaar update centre",
    where_to_get_hi: "टेलीकॉम स्टोर या आधार अपडेट केंद्र पर लिंक करें",
  },
  passport_photo: {
    slug: "passport_photo",
    label_en: "Passport-size Photograph",
    label_hi: "पासपोर्ट आकार का फोटो",
    description_en: "Recent colour photograph on white background.",
    description_hi: "सफेद पृष्ठभूमि पर हालिया रंगीन फोटो।",
    where_to_get_en: "Any photo studio or Common Service Centre",
    where_to_get_hi: "कोई भी फोटो स्टूडियो या सामान्य सेवा केंद्र",
  },
  bank_statements: {
    slug: "bank_statements",
    label_en: "Bank Statements (6 months)",
    label_hi: "बैंक स्टेटमेंट (6 महीने)",
    description_en: "Last 6 months bank account statement.",
    description_hi: "पिछले 6 महीनों का बैंक खाता विवरण।",
    where_to_get_en: "Bank branch or net banking download",
    where_to_get_hi: "बैंक शाखा या नेट बैंकिंग से डाउनलोड",
  },
  trade_certificate_or_self_declaration: {
    slug: "trade_certificate_or_self_declaration",
    label_en: "Trade Certificate or Self-Declaration",
    label_hi: "व्यापार प्रमाण पत्र या स्व-घोषणा",
    description_en: "Proof of engagement in traditional trade/craft.",
    description_hi: "पारंपरिक व्यापार/शिल्प में संलग्नता का प्रमाण।",
    where_to_get_en: "Local artisan guild or self-declaration on PM Vishwakarma portal",
    where_to_get_hi: "स्थानीय शिल्पकार संघ या पीएम विश्वकर्मा पोर्टल पर स्व-घोषणा",
  },
  mobile_linked_aadhaar: {
    slug: "mobile_linked_aadhaar",
    label_en: "Mobile Linked to Aadhaar",
    label_hi: "आधार से लिंक मोबाइल",
    description_en: "Mobile number registered with Aadhaar for scheme notifications.",
    description_hi: "योजना सूचनाओं के लिए आधार से पंजीकृत मोबाइल नंबर।",
    where_to_get_en: "UIDAI or telecom operator linking service",
    where_to_get_hi: "यूआईडीएआई या टेलीकॉम ऑपरेटर लिंकिंग सेवा",
  },
};

export function getDocumentInfo(slug: string): DocumentInfo {
  return (
    DOCUMENT_REGISTRY[slug] || {
      slug,
      label_en: slug.replace(/_/g, " "),
      label_hi: slug.replace(/_/g, " "),
      description_en: "Required document for this scheme.",
      description_hi: "इस योजना के लिए आवश्यक दस्तावेज़।",
      where_to_get_en: "Contact your local government office or CSC.",
      where_to_get_hi: "स्थानीय सरकारी कार्यालय या सीएससी से संपर्क करें।",
    }
  );
}
